### ISSUE TITLE
Component: Add support for badge component

### ISSUE THREAD

**Issue by tewshi** [rotki/ui-library#112]
## Description

Add badge component

[Figma Design](https://www.figma.com/file/msxmKajRPLYiDDmsP60Ndh/Design-System-v1.1?type=design&node-id=13-36978&mode=dev)

## Tasks

- [x] support dots
- [x] support badge label, label + icon, icon
- [x] support different sizes
- [x] support left and right positions
- [x] support top, center and bottom placements
- [x] support theme colours / theme modes
