### ISSUE TITLE
Button Toggle: Create button toggle component

### ISSUE THREAD

**Issue by tewshi** [rotki/ui-library#27]
## Description

as per out [Figma design](https://www.figma.com/file/msxmKajRPLYiDDmsP60Ndh/Design-System-v1.1?type=design&node-id=597-48079&t=L48IjHMRx8pw5v5x-4)

create a component for this use-case

## Tasks

- [ ] allows different sizes
- [ ] allows selecting single (default) or multiple
- [ ] support light/dark mode
- [ ] support icons as well as text content or slot
