### ISSUE TITLE
Feature: Create Dialog component

### ISSUE THREAD

**Issue by tewshi** [rotki/ui-library#91]
## Description

as part of the next milestone, we need to add the dialog component.

[Figma Design](https://www.figma.com/file/msxmKajRPLYiDDmsP60Ndh/Design-System-v1.1?type=design&node-id=576-55099&mode=dev)

## Tasks

should support:

- [ ] title, content and action areas
- [ ] clickable / dismissible overlay
- [ ] persistent modals that close only via action buttons
- [ ] light / dark mode
