### ISSUE TITLE
Add more functional tests for Table component

### ISSUE THREAD

**Issue by tewshi** [rotki/ui-library#97]
## Description

Table component has a few tests, need to include more for other functionalities

## Tasks

- [ ] test pagination
- [ ] test searching
- [ ] test sorting
- [ ] test API controlled pagination
- [ ] test API controlled searching
- [ ] test API controlled sorting
